TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += cp2800.db

#protocol files
DATA += cp2800.proto

#=======================================
include $(TOP)/configure/RULES
